# Generated by Django 4.0.6 on 2023-01-20 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='victor_codes.png', upload_to='post_images/'),
        ),
    ]
